In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nunenuh/pytorch-challange-flower-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/pytorch-challange-flower-dataset


In [ ]:
import numpy as np
import pandas as pd

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/pytorch-challange-flower-dataset'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


In [ ]:
path= "/kaggle/input/pytorch-challange-flower-dataset/dataset/"
folders=os.listdir(path)

print(folders)

['valid', 'test', 'train']


In [ ]:
import matplotlib
matplotlib.use("Agg")
# import the necessary packages
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import img_to_array
import matplotlib.pyplot as plt
import numpy as np
import argparse
import random
import cv2

In [ ]:
train_dir="/kaggle/input/pytorch-challange-flower-dataset/dataset/train/"
valid_dir="/kaggle/input/pytorch-challange-flower-dataset/dataset/valid/"


In [ ]:
train_gen=ImageDataGenerator(rescale=1./255)
val_gen=ImageDataGenerator(rescale=1./255)
#test_gen=ImageDataGenerator(rescale=1./255)

In [ ]:
train_data=train_gen.flow_from_directory(train_dir,target_size=(224,224),
                                         batch_size=32,class_mode='categorical')
valid_data=val_gen.flow_from_directory(valid_dir,target_size=(224,224),
                                         batch_size=32,class_mode='categorical')


Found 6552 images belonging to 102 classes.
Found 818 images belonging to 102 classes.


In [ ]:

# Retrieve one batch of images and labels
images, labels = next(train_data)
print(images.shape,labels)
# Display the first image in the batch
plt.imshow(images[0])
plt.axis('off')  # Hide axis
predicted_class_index = np.argmax(labels[0])
plt.title(f"Label: {predicted_class_index}")  # Display label using the predicted class index
plt.show()

(32, 224, 224, 3) [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
class_indices = train_data.class_indices
print(class_indices)

{'1': 0, '10': 1, '100': 2, '101': 3, '102': 4, '11': 5, '12': 6, '13': 7, '14': 8, '15': 9, '16': 10, '17': 11, '18': 12, '19': 13, '2': 14, '20': 15, '21': 16, '22': 17, '23': 18, '24': 19, '25': 20, '26': 21, '27': 22, '28': 23, '29': 24, '3': 25, '30': 26, '31': 27, '32': 28, '33': 29, '34': 30, '35': 31, '36': 32, '37': 33, '38': 34, '39': 35, '4': 36, '40': 37, '41': 38, '42': 39, '43': 40, '44': 41, '45': 42, '46': 43, '47': 44, '48': 45, '49': 46, '5': 47, '50': 48, '51': 49, '52': 50, '53': 51, '54': 52, '55': 53, '56': 54, '57': 55, '58': 56, '59': 57, '6': 58, '60': 59, '61': 60, '62': 61, '63': 62, '64': 63, '65': 64, '66': 65, '67': 66, '68': 67, '69': 68, '7': 69, '70': 70, '71': 71, '72': 72, '73': 73, '74': 74, '75': 75, '76': 76, '77': 77, '78': 78, '79': 79, '8': 80, '80': 81, '81': 82, '82': 83, '83': 84, '84': 85, '85': 86, '86': 87, '87': 88, '88': 89, '89': 90, '9': 91, '90': 92, '91': 93, '92': 94, '93': 95, '94': 96, '95': 97, '96': 98, '97': 99, '98': 100, '99'

In [ ]:
#Compile the model
print("[INFO] compiling model...")
opt = Adam()
model.compile(loss="categorical_crossentropy", optimizer=opt,
	metrics=["accuracy"])

[INFO] compiling model...


In [ ]:
# Define the checkpoint callback
import tensorflow
checkpoint =tensorflow.keras.callbacks.ModelCheckpoint(
    filepath='path/model_epoch_{epoch:02d}.h5',  # Save the model with epoch number
    save_freq='epoch',                      # Save at the end of every epoch
    save_weights_only=False,                # Save the entire model (architecture + weights)
    verbose=1                               # Print a message when saving
)

print(len(train_data))

205


In [ ]:
#train the model
# train the network
print("[INFO] training network...")
print("[INFO] training network...")
H = model.fit(train_data,
            validation_data=valid_data,
						callbacks=[checkpoint],
						epochs=10)

[INFO] training network...
[INFO] training network...
Epoch 1/10
205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.9386 - loss: 0.2576
Epoch 1: saving model to path/model_epoch_01.h5


205/205 ━━━━━━━━━━━━━━━━━━━━ 34s 167ms/step - accuracy: 0.9386 - loss: 0.2576 - val_accuracy: 0.3716 - val_loss: 3.1699
Epoch 2/10
205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.9907 - loss: 0.0468
Epoch 2: saving model to path/model_epoch_02.h5


205/205 ━━━━━━━━━━━━━━━━━━━━ 35s 168ms/step - accuracy: 0.9907 - loss: 0.0468 - val_accuracy: 0.3594 - val_loss: 3.7580
Epoch 3/10
205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.9939 - loss: 0.0263
Epoch 3: saving model to path/model_epoch_03.h5


205/205 ━━━━━━━━━━━━━━━━━━━━ 33s 160ms/step - accuracy: 0.9939 - loss: 0.0262 - val_accuracy: 0.4156 - val_loss: 3.8486
Epoch 4/10
205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.9971 - loss: 0.0100
Epoch 4: saving model to path/model_epoch_04.h5


205/205 ━━━━━━━━━━━━━━━━━━━━ 36s 178ms/step - accuracy: 0.9972 - loss: 0.0100 - val_accuracy: 0.4205 - val_loss: 3.8492
Epoch 5/10
205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 1.0000 - loss: 4.8491e-04
Epoch 5: saving model to path/model_epoch_05.h5


205/205 ━━━━━━━━━━━━━━━━━━━━ 32s 156ms/step - accuracy: 1.0000 - loss: 4.8450e-04 - val_accuracy: 0.4352 - val_loss: 3.9156
Epoch 6/10
205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 1.0000 - loss: 2.1497e-04
Epoch 6: saving model to path/model_epoch_06.h5


205/205 ━━━━━━━━━━━━━━━━━━━━ 34s 164ms/step - accuracy: 1.0000 - loss: 2.1485e-04 - val_accuracy: 0.4401 - val_loss: 4.0014
Epoch 7/10
205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 1.0000 - loss: 1.4148e-04
Epoch 7: saving model to path/model_epoch_07.h5


205/205 ━━━━━━━━━━━━━━━━━━━━ 33s 160ms/step - accuracy: 1.0000 - loss: 1.4144e-04 - val_accuracy: 0.4438 - val_loss: 4.0679
Epoch 8/10
205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 1.0000 - loss: 1.0033e-04
Epoch 8: saving model to path/model_epoch_08.h5


205/205 ━━━━━━━━━━━━━━━━━━━━ 33s 160ms/step - accuracy: 1.0000 - loss: 1.0034e-04 - val_accuracy: 0.4474 - val_loss: 4.1271
Epoch 9/10
205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 1.0000 - loss: 8.1140e-05
Epoch 9: saving model to path/model_epoch_09.h5


205/205 ━━━━━━━━━━━━━━━━━━━━ 33s 159ms/step - accuracy: 1.0000 - loss: 8.1134e-05 - val_accuracy: 0.4487 - val_loss: 4.1802
Epoch 10/10
205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 1.0000 - loss: 6.7432e-05
Epoch 10: saving model to path/model_epoch_10.h5


205/205 ━━━━━━━━━━━━━━━━━━━━ 34s 167ms/step - accuracy: 1.0000 - loss: 6.7420e-05 - val_accuracy: 0.4474 - val_loss: 4.2311


In [ ]:
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import load_img, img_to_array
import numpy as np
model = load_model('/content/path/model_epoch_10.h5')

# Load the image with the same target size as used during training
img = load_img('/content/path/Shoe-flower.jpg', target_size=(224,224))

# Convert the image to a NumPy array
img_array = img_to_array(img)

# Normalize the image data if the model was trained on normalized data
img_array = img_array / 255.0

# Expand dimensions to match the model's input shape (1, height, width, channels)
img_array = np.expand_dims(img_array, axis=0)
predictions = model.predict(img_array)
predicted_class = np.argmax(predictions, axis=1)
print(predicted_class[0]) ## numerically
print(class_indices[predicted_class[0]]) ## categorical prediction

In [ ]:
import tensorflow
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input
from tensorflow.keras import layers
from tensorflow.keras.layers import Dropout
vgg_base = VGG16(weights='imagenet', include_top=False, input_shape=(224,224,3))
vgg_base.trainable = False

model = Sequential()
model.add(vgg_base)
model.add(Flatten())
model.add(Dropout(0.5))
model.add(Dense(1024, activation='relu', name='fc1'))
model.add(Dense(102, activation='softmax', name='output'))
model.summary()


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ vgg16 (Functional)              │ (None, 7, 7, 512)      │    14,714,688 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_8 (Flatten)             │ (None, 25088)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 25088)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc1 (Dense)                     │ (None, 1024)           │    25,691,136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 102)            │       104,550 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40,510,374 (154.53 MB)

 Trainable params: 25,795,686 (98.40 MB)

 Non-trainable params: 14,714,688 (56.13 MB)